"use client";

import { useState } from "react";
import { promiseTemplates, type CreateBackInput, type CreateBackResult } from "@/lib/backs/model";
import { validateCreateBack, type ValidationErrors } from "@/lib/validation/create-back";
import { BrandedDatePicker } from "@/components/forms/BrandedDatePicker";
import { MoneyInput } from "@/components/forms/MoneyInput";
import { currencySymbol } from "@/lib/money/currency";
import { BackedMark } from "@/components/brand/BackedMark";

const initial: CreateBackInput = { backerName:"",achieverFirstName:"",achieverLastName:"",achieverContact:"",templateKey:"first_half",promiseTitle:"Run my first half marathon",deadline:"",successCriteria:"Complete an official half marathon before the deadline.",verificationMethod:"Official race result",amountMinor:5000,currency:"USD",message:"" };
const labels=["Person","Promise","Amount","Message","Review"];

export function CreateBackFlow(){
  const [step,setStep]=useState(0); const [data,setData]=useState(initial); const [errors,setErrors]=useState<ValidationErrors>({}); const [busy,setBusy]=useState(false); const [result,setResult]=useState<CreateBackResult|null>(null); const [failure,setFailure]=useState("");
  const amount=data.amountMinor/100;
  const update=<K extends keyof CreateBackInput>(key:K,value:CreateBackInput[K])=>{setData(current=>({...current,[key]:value}));setErrors(current=>({...current,[key]:undefined}))};
  const next=()=>{ const all=validateCreateBack(data); const relevant:ValidationErrors={}; const keys:Record<number,(keyof CreateBackInput)[]>={0:["backerName","achieverFirstName","achieverContact"],1:["templateKey","promiseTitle","deadline","successCriteria","verificationMethod"],2:["amountMinor"],3:["message"],4:[]}; keys[step].forEach(key=>{if(all[key]) relevant[key]=all[key]}); if(Object.keys(relevant).length){setErrors(relevant);return} setStep(value=>Math.min(4,value+1)); window.scrollTo({top:0,behavior:"smooth"}); };
  const submit=async()=>{const validation=validateCreateBack(data);if(Object.keys(validation).length){setErrors(validation);return}setBusy(true);setFailure("");try{const response=await fetch("/api/backs",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const body=await response.json() as CreateBackResult&{error?:string;errors?:ValidationErrors};if(!response.ok){setErrors(body.errors??{});throw new Error(body.error??"Please check the details and try again.")}setResult(body)}catch(error){setFailure(error instanceof Error?error.message:"Please try again.")}finally{setBusy(false)}};
  if(result) return <section className="inviteMoment"><div className="brandMark big"><BackedMark/></div><p className="eyebrow">BACK CREATED · INVITE READY</p><h1>{data.achieverFirstName.toUpperCase()}<br/>IS BACKED<span>.</span></h1><strong>${amount.toLocaleString()}</strong><p>behind {data.achieverFirstName}.</p><div className="inviteStatus"><span>Promise proposed</span><span>Commitment mocked</span><span>{result.requiresManualReview?"Manual review required":"Invite ready"}</span></div><p className="alphaNotice light">Alpha preview: no invite message was actually sent, and no money was collected — the commitment above is mocked.</p><button className="button primary" onClick={()=>{setResult(null);setData(initial);setStep(0)}}>BACK SOMEONE ELSE <span>→</span></button></section>;
  return <section className="flowShell"><header className="flowHeader"><div><p className="eyebrow">CREATE A BACK</p><span>{String(step+1).padStart(2,"0")} / 05</span></div><ol aria-label="Progress">{labels.map((label,index)=><li className={index===step?"active":index<step?"done":""} key={label}><i/><span>{label}</span></li>)}</ol></header>
    <div className="flowPanel">
      {step===0&&<div className="flowStep"><p className="eyebrow">THE PERSON</p><h1>WHO DO YOU<br/>BELIEVE IN<span>?</span></h1><p className="stepIntro">Start with the person. They don’t need an account yet.</p><Field label="Your name" error={errors.backerName}><input value={data.backerName} onChange={e=>update("backerName",e.target.value)} autoComplete="name" placeholder="Matthew"/></Field><div className="fieldGrid two"><Field label="First name" error={errors.achieverFirstName}><input value={data.achieverFirstName} onChange={e=>update("achieverFirstName",e.target.value)} autoComplete="given-name" placeholder="Jason"/></Field><Field label="Last name · optional"><input value={data.achieverLastName} onChange={e=>update("achieverLastName",e.target.value)} autoComplete="family-name" placeholder="Morgan"/></Field></div><Field label="Email or mobile" error={errors.achieverContact}><input value={data.achieverContact} onChange={e=>update("achieverContact",e.target.value)} autoComplete="email" placeholder="jason@example.com"/></Field></div>}
      {step===1&&<div className="flowStep"><p className="eyebrow">THE PROMISE</p><h1>WHAT CAN THEY<br/>DO<span>?</span></h1><div className="templateGrid">{promiseTemplates.map(item=><button type="button" className={data.templateKey===item.key?"selected":""} onClick={()=>{update("templateKey",item.key);if(item.key!=="custom")update("promiseTitle",item.label)}} key={item.key}><i/>{item.label}</button>)}</div><Field label="Promise title" error={errors.promiseTitle}><input maxLength={100} value={data.promiseTitle} onChange={e=>update("promiseTitle",e.target.value)}/></Field><div className="fieldGrid two"><Field label="Deadline" error={errors.deadline}><BrandedDatePicker value={data.deadline} onChange={value=>update("deadline",value)}/></Field><Field label="Verification" error={errors.verificationMethod}><input maxLength={200} value={data.verificationMethod} onChange={e=>update("verificationMethod",e.target.value)}/></Field></div><Field label="What counts as success?" error={errors.successCriteria}><textarea maxLength={400} value={data.successCriteria} onChange={e=>update("successCriteria",e.target.value)}/></Field></div>}
      {step===2&&<div className="flowStep"><p className="eyebrow">THE BACKING</p><h1>PUT SOMETHING<br/>BEHIND THEM<span>.</span></h1><div className="moneyChoices">{[25,50,100,250].map(value=><button type="button" className={amount===value?"selected":""} onClick={()=>update("amountMinor",value*100)} key={value}>{currencySymbol(data.currency)}{value}</button>)}</div><Field label={`Other amount · ${data.currency}`} error={errors.amountMinor}><MoneyInput value={amount} currency={data.currency} onChange={value=>update("amountMinor",value*100)}/></Field><p className="safetyCopy">Currency will follow the backer’s profile when profiles are connected. This creates a conditional backing commitment; BACKED does not collect or hold money in this Alpha.</p></div>}
      {step===3&&<div className="flowStep"><p className="eyebrow">THE MESSAGE</p><h1>SAY SOMETHING<br/>THEY’LL NEED<span>.</span></h1><Field label="Your message · optional" error={errors.message}><textarea className="messageInput" maxLength={280} value={data.message} onChange={e=>update("message",e.target.value)} placeholder="You’ve talked about doing this forever. Time to do it."/></Field><p className="charCount">{data.message?.length??0} / 280</p></div>}
      {step===4&&<div className="flowStep reviewStep"><p className="eyebrow">REVIEW YOUR BACK</p><div className="reviewPerson"><span>FOR</span><h1>{data.achieverFirstName.toUpperCase()}</h1><button onClick={()=>setStep(0)}>EDIT</button></div><div className="reviewPromise"><span>YOU BELIEVE THEY CAN</span><h2>{data.promiseTitle}</h2><p>by {new Date(`${data.deadline}T12:00:00`).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</p><button onClick={()=>setStep(1)}>EDIT</button></div><div className="reviewMoney"><strong>${amount.toLocaleString()}</strong><span>behind {data.achieverFirstName}.</span><button onClick={()=>setStep(2)}>EDIT</button></div>{data.message&&<blockquote>“{data.message}”</blockquote>}<p className="safetyCopy">Continuing creates a real invite for {data.achieverFirstName||"them"}, with a mocked conditional commitment. No payment is collected and no message is sent.</p>{failure&&<p className="formError" role="alert">{failure}</p>}</div>}
    </div><footer className="flowActions">{step>0&&<button className="backButton" onClick={()=>setStep(value=>value-1)}>← BACK</button>}<button className="button primary" disabled={busy} onClick={step===4?submit:next}>{busy?"CREATING…":step===4?`BACK ${data.achieverFirstName.toUpperCase()} $${amount}`:"CONTINUE"}<span>→</span></button></footer>
  </section>;
}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="flowField"><span>{label}</span>{children}{error&&<small role="alert">{error}</small>}</label>}
