// Hand-written SQL in db/migrations is authoritative; this file is kept in sync manually
// (drizzle-kit generate has no journal to diff against and will not detect drift).
import { pgEnum, pgTable, text, timestamp, uuid, integer, char, jsonb, date, uniqueIndex } from "drizzle-orm/pg-core";
export const promiseState=pgEnum("promise_state",["proposed","accepted","active","proof_pending","verified","completed","declined","expired","ended_unverified","cancelled_by_admin"]);
export const backState=pgEnum("back_state",["proposed","committed","active","payable","released","declined","cancelled","expired","returned","payment_failed"]);
export const visibility=pgEnum("visibility",["private","circle","public"]);
const timestamps={createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull(),updatedAt:timestamp("updated_at",{withTimezone:true}).defaultNow().notNull()};
export const users=pgTable("users",{id:uuid("id").defaultRandom().primaryKey(),email:text("email"),phone:text("phone"),...timestamps,lastSeenAt:timestamp("last_seen_at",{withTimezone:true})},(table)=>[uniqueIndex("users_email_unique").on(table.email)]);
export const profiles=pgTable("profiles",{userId:uuid("user_id").primaryKey().references(()=>users.id),firstName:text("first_name").notNull(),lastName:text("last_name"),displayName:text("display_name").notNull(),avatarUrl:text("avatar_url"),bio:text("bio"),slug:text("slug").unique(),locale:text("locale").default("en").notNull(),timezone:text("timezone").default("UTC").notNull(),...timestamps});
export const promises=pgTable("promises",{id:uuid("id").defaultRandom().primaryKey(),ownerUserId:uuid("owner_user_id").notNull().references(()=>users.id),creatorUserId:uuid("creator_user_id").references(()=>users.id),title:text("title").notNull(),category:text("category").notNull(),templateKey:text("template_key"),description:text("description"),deadline:timestamp("deadline",{withTimezone:true}).notNull(),successCriteria:text("success_criteria").notNull(),verificationMethod:text("verification_method").notNull(),visibility:visibility().default("circle").notNull(),state:promiseState().default("proposed").notNull(),slug:text("slug").notNull().unique(),heroImageUrl:text("hero_image_url"),acceptedAt:timestamp("accepted_at",{withTimezone:true}),activatedAt:timestamp("activated_at",{withTimezone:true}),proofSubmittedAt:timestamp("proof_submitted_at",{withTimezone:true}),verifiedAt:timestamp("verified_at",{withTimezone:true}),completedAt:timestamp("completed_at",{withTimezone:true}),endedAt:timestamp("ended_at",{withTimezone:true}),...timestamps});
export const backs=pgTable("backs",{id:uuid("id").defaultRandom().primaryKey(),promiseId:uuid("promise_id").references(()=>promises.id),backerUserId:uuid("backer_user_id").references(()=>users.id),recipientUserId:uuid("recipient_user_id").references(()=>users.id),amountMinor:integer("amount_minor").notNull(),currency:char("currency",{length:3}).default("USD").notNull(),state:backState().default("proposed").notNull(),message:text("message"),...timestamps});
export const backingCommitments=pgTable("backing_commitments",{id:uuid("id").defaultRandom().primaryKey(),backId:uuid("back_id").notNull().unique().references(()=>backs.id),provider:text("provider").notNull(),providerCustomerRef:text("provider_customer_ref"),providerPaymentMethodRef:text("provider_payment_method_ref"),commitmentState:text("commitment_state").notNull(),authorizedAt:timestamp("authorized_at",{withTimezone:true}),payableAt:timestamp("payable_at",{withTimezone:true}),releasedAt:timestamp("released_at",{withTimezone:true}),expiredAt:timestamp("expired_at",{withTimezone:true}),...timestamps});
export const paymentEvents=pgTable("payment_events",{id:uuid("id").defaultRandom().primaryKey(),backId:uuid("back_id").notNull().references(()=>backs.id),type:text("type").notNull(),provider:text("provider").notNull(),providerEventId:text("provider_event_id"),amountMinor:integer("amount_minor"),currency:char("currency",{length:3}),payloadJson:jsonb("payload_json").default({}).notNull(),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const invites=pgTable("invites",{id:uuid("id").defaultRandom().primaryKey(),backId:uuid("back_id").notNull().references(()=>backs.id),promiseId:uuid("promise_id").notNull().references(()=>promises.id),tokenHash:text("token_hash").notNull().unique(),expiresAt:timestamp("expires_at",{withTimezone:true}).notNull(),acceptedAt:timestamp("accepted_at",{withTimezone:true}),revokedAt:timestamp("revoked_at",{withTimezone:true}),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
export const progressUpdates=pgTable("progress_updates",{id:uuid("id").defaultRandom().primaryKey(),promiseId:uuid("promise_id").notNull().references(()=>promises.id),authorUserId:uuid("author_user_id").notNull().references(()=>users.id),title:text("title"),body:text("body"),mediaUrl:text("media_url"),activityDistanceM:integer("activity_distance_m"),activityDurationS:integer("activity_duration_s"),activityDate:date("activity_date"),...timestamps});
export const proofSubmissions=pgTable("proof_submissions",{id:uuid("id").defaultRandom().primaryKey(),promiseId:uuid("promise_id").notNull().references(()=>promises.id),submittedBy:uuid("submitted_by").notNull().references(()=>users.id),note:text("note"),proofUrl:text("proof_url"),resultUrl:text("result_url"),state:text("state").default("pending").notNull(),...timestamps});
export const verifications=pgTable("verifications",{id:uuid("id").defaultRandom().primaryKey(),proofSubmissionId:uuid("proof_submission_id").notNull().references(()=>proofSubmissions.id),reviewerUserId:uuid("reviewer_user_id").notNull().references(()=>users.id),decision:text("decision").notNull(),note:text("note"),createdAt:timestamp("created_at",{withTimezone:true}).defaultNow().notNull()});
